### PR TITLE
Initialize project

### PR DESCRIPTION
**Pull request by AnselemOdims**
# Steps
- Installed necessary dependencies
- Removed unwanted boilerplate files
- Configured the linters
- Built out the components
- Added react-router for the two pages
- Installed react-redux for state-management

### CODE REVIEW

**Review by D4nielJ — CHANGES_REQUESTED** [review]
## Hello @AnselemOdims, 

You're doing great! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :fire: :rocket:
- Everything looks great!
- Good use of components
- Well-structured project! :clap:

## Required Changes ♻️

- [ ] I think it would be nice to include the README from the [Microverse Templates](https://github.com/microverseinc/readme-template). This will help us keep the repository professional; although the README from CRA is not bad, it does look really generic.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AnselemOdims** [comment]
Ok thanks @D4nielJ

**Review by D4nielJ — APPROVED** [review]
## Hello @AnselemOdims, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AnselemOdims** [comment]
Thanks @D4nielJ

**Pull request merged**
